# Site settings
name: TodayRun Blog
email: 524914439@qq.com
author: Mr.Huo
url:  https://todayrun.github.io/
resume_site:  https://todayrun.github.io/
github:  https://todayrun.github.io/
#特别注意`baseurl`的配置。如果是`***.github.io`项目，不修改为空''的话，会导致JS,CSS等静态资源无法找到的错误
#baseurl: "/LessOrMore"
baseurl: ''
description: Practice is the sole criterion for testing truth!
motto: TodayRun Blog
banner: Practice is the sole criterion for testing truth!

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']


# Build settings
markdown: 

baidu_analysis: 

